### ISSUE TITLE
azimuth gap

### ISSUE THREAD

**Issue by adokter** [NLeSC/enram#64]
add azimuth_gap() check as a condition for running svd_fit()

**Comment by jspaaks** [comment]
``svdfit``'s main result is an optimal parameter set (3-vector), but the method does not provide any estimate of uncertainty. This can be a problem for data sets that have data exclusively on one side of the radar. Running ``svdfit`` on such data leads to a false suggestion of accuracy. For the moment, the ``azimuth_gap()`` should test if there are any large gaps in the data, and if so, skip the analysis altogether.

**Comment by jspaaks** [comment]
Should be fixed in commit 96339454b69dda864c6ae6cd93b65c6a34fcc5c4 (but note that the list that is provided to ``hasAzimuthGap()`` is still not the right list
