### ISSUE TITLE
no STDEVBIRD check when converting reflectivity to bird density

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/enram#70]
* [reference code] (https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L698-L707) 
* [what I think should be the place to add it](https://github.com/NLeSC/enram/blob/fd18b521bcfc75dbab892cbc5d3f3aa3301651b4/ncradar/lib/vol2bird/libvol2bird.c#L597-L600)

Would it be possible to manage including/excluding of certain gates based on another flag using the ``includeGate()`` and ``classifyGatesSimple()`` methods?

Question @adokter: what does it this check do conceptually?

**Comment by adokter** [comment]
1. Take the `chi` that you calculate [here](https://github.com/NLeSC/enram/blob/fd18b521bcfc75dbab892cbc5d3f3aa3301651b4/ncradar/lib/vol2bird/libvol2bird.c#L630) for `iProfileType==3`

(https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L831-L841)

**Comment by jspaaks** [comment]
Here's what I propose. I'll change the program to always calculate 3 profiles but in a different order: 3, 2, 1 rather than 1, 2, 3. When I'm calculating ``iProfileType==3``, I can fill an int array list with ``nLayers`` elements, with either ``TRUE`` or ``FALSE`` values, depending on the result of ``chi<STDEVBIRD``. This array can then later be used when processing ``iProfileType==1``. Sounds good?

**Comment by adokter** [comment]
Sounds good!

**Comment by jspaaks** [comment]
Fixed in commit c4276ed2243dc62c188e4607f8ad1ff33d073037. Closing the issue.
