### ISSUE TITLE
write optional ODIM_H5 volume file with added cell/clutter fields

### ISSUE THREAD

**Issue by adokter** [NLeSC/enram#81]
following up on issue #79: optional output is currently to stderr only. Output to a single hdf5 file is much easier (convenient hdf5 viewers exist by which users can rapidly inspect the raw data as images, especially if you include appropriate color pallettes for each images)

see implementation:
https://github.com/NLeSC/enram/blob/master/doc/vol2bird-adriaans-version-20140716/vol2birdprof_h5.c#L1934-L2004

**Comment by jspaaks** [comment]
I think it's better to first make sure to write profiled/non-profiled data back to a RAVE object (issue #78), then use other tools from the BALTRAD toolbox to write ODIMH5. No use redoing what has already been done by the BALTRAD guys.

**Comment by adokter** [comment]
Yes fully agree, this issue is the same as issue #78 but then for non-profiled data

**Comment by jspaaks** [comment]
This approach would work on local files, but see my prefered approach (issue #93)
