### ISSUE TITLE
Why change the number of gates when dropping a cell

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/enram#89]
see code snippet [here](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L535-L571). Also affects 
* [this](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L585-L587)  part in ``analyzeCells``
* this part [here](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L2189) in ``sortCells()``
* [here](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L2203) in ``sortCells()``
* [this part](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L2307-L2309) in ``updatemap()``

**Comment by jspaaks** [comment]
should be fixed by commit 875909dcf8fcbaacdf7c500fa421cd4aace09f72.

**Comment by adokter** [comment]
Indeed sortcells was sorting only the cells that were not dropped. When sorting by cellarea, I apparently used an area of zero to indicate the cell was dropped. Having a separate function for removing dropped cells increases the readability indeed
