### ISSUE TITLE
convoluted while condition in sortCells()

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/enram#91]
**nobody** knows what [this](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L2203) means. Simplify, it is far from performance critical

**Comment by jspaaks** [comment]
This issue was resolved by commit 875909dcf8fcbaacdf7c500fa421cd4aace09f72

**Comment by jspaaks** [comment]
@adokter could you verify this plz

**Comment by adokter** [comment]
[this](https://github.com/NLeSC/enram/blob/68303a8cb91b3c2a1280a528c43d233c215ee6f7/ncradar/lib/vol2bird/libvol2bird.c#L2203) removed the dropped cells in the sort. Now you have a separate function for this task, looks ok.
